export enum TipoPractica {
    PRACTICA_UNO = "PRACTICA_UNO",
    PRACTICA_DOS = "PRACTICA_DOS"
  }
  
  export enum TipoUsuario {
    JEFE_CARRERA = "JEFE_CARRERA",
    ALUMNO_PRACTICA = "ALUMNO_PRACTICA",
    JEFE_DEPARTAMENTO = "JEFE_DEPARTAMENTO",
    SECRETARIA_DEPARTAMENTO = "SECRETARIA_DEPARTAMENTO",
    SECRETARIA_CARRERA = "SECRETARIA_CARRERA",
    JEFE_EMPLEADOR = "JEFE_EMPLEADOR",
    ADMINISTRADOR = "ADMINISTRADOR",
    ACADEMICO = "ACADEMICO"
  }
  
 export enum ModalidadPractica {
    PRESENCIAL = "PRESENCIAL",
    SEMI_PRESENCIAL = "SEMI_PRESENCIAL",
    REMOTO = "REMOTO"
  }
  
 export enum TipoPregunta {
    ABIERTA = "ABIERTA",
    CERRADA = "CERRADA",
    DESARROLLO_PROFESIONAL = "DESARROLLO_PROFESIONAL",
    REVISION_ACADEMICA = "REVISION_ACADEMICA",
    VINCULACION_MEDIO = 'VINCULACION_MEDIO',
    HABILIDADES_TECNICAS = 'HABILIDADES_TECNICAS',
    SALARIO_ESTIMADO = 'SALARIO_ESTIMADO'
  }
  
  export enum EstadoInforme {
    ENVIADA = "ENVIADA",
    REVISION = "REVISION",
    APROBADA = "APROBADA",
    CORRECCION = "CORRECCION",
    DESAPROBADA = "DESAPROBADA",
    ESPERA = "ESPERA"
  }
  
  export enum EstadoPractica {
    CURSANDO = "CURSANDO",
    ESPERA_INFORMES = "ESPERA_INFORMES",
    REVISION_GENERAL = "REVISION_GENERAL",
    FINALIZADA = "FINALIZADA",
    INFORMES_RECIBIDOS = "INFORMES_RECIBIDOS"
  }
  
 export enum TipoAsignatura {
    FORMACION_BASICA = "FORMACION_BASICA",
    FORMACION_GENERAL = "FORMACION_GENERAL",
    FORMACION_PROFESIONAL = "FORMACION_PROFESIONAL"
  }