export enum TipoPractica {
    PRACTICA_UNO = "PRACTICA_UNO",
    PRACTICA_DOS = "PRACTICA_DOS"
  }
  
  export enum TipoUsuario {
    JEFE_CARRERA = "JEFE_CARRERA",
    ALUMNO_PRACTICA = "ALUMNO_PRACTICA",
    JEFE_DEPARTAMENTO = "JEFE_DEPARTAMENTO",
    SECRETARIA = "SECRETARIA",
    JEFE_EMPLEADOR = "JEFE_EMPLEADOR"
  }
  
 export enum ModalidadPractica {
    PRESENCIAL = "PRESENCIAL",
    SEMI_PRESENCIAL = "SEMI_PRESENCIAL",
    REMOTO = "REMOTO"
  }
  
 export enum TipoPregunta {
    ABIERTA = "ABIERTA",
    CERRADA = "CERRADA",
    EVALUATIVA = "EVALUATIVA",
    DESARROLLO_PROFESIONAL = "DESARROLLO_PROFESIONAL"
  }
  
  export enum EstadoInforme {
    ENVIADA = "ENVIADA",
    REVISION = "REVISION",
    APROBADA = "APROBADA",
    CORRECCION = "CORRECCION",
    DESAPROBADA = "DESAPROBADA"
  }
  
  export enum EstadoPractica {
    CURSANDO = "CURSANDO",
    ESPERA_INFORME_ALUMNO = "ESPERA_INFORME_ALUMNO",
    REVISION_INFORME_ALUMNO = "REVISION_INFORME_ALUMNO",
    CORRECCION_INFORME_ALUMNO = "CORRECCION_INFORME_ALUMNO",
    ESPERA_INFORME_CONFIDENCIAL = "ESPERA_INFORME_CONFIDENCIAL",
    REVISION_GENERAL = "REVISION_GENERAL",
    FINALIZADA = "FINALIZADA"
  }
  
 export enum TipoAsignatura {
    FORMACION_BASICA = "FORMACION_BASICA",
    FORMACION_GENERAL = "FORMACION_GENERAL",
    FORMACION_PROFESIONAL = "FORMACION_PROFESIONAL"
  }